#!/bin/sh

. ~/.dockerfunc

NAME=grafana-plugin
TAGNAME=shellicar/grafana-plugin
SOURCE_PLUGIN=${HOME}/host/plugins/sensorcloud/

del_stopped ${NAME}
docker run \
    --rm \
    -it \
    --name "${NAME}" \
    -v ${SOURCE_PLUGIN}:/root/plugin/ \
    -v grafana-plugin-node-modules:/root/plugin/node_modules/ \
    ${TAGNAME} \
    /bin/bash

